name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  
          cache: 'yarn'
          cache-dependency-path: './app/yarn.lock'

      - name: Install Dependencies
        run: yarn install
        working-directory: ./app

      - name: Run Tests
        run: yarn test
        working-directory: ./app
